---
- name: starting automation controller 
  hosts: localhost
  remote_user: root
  tasks:
    - name:
      shell: /root/service.sh
      register: ALL_service_status
    - name: showing report
      debug: 
        var: ALL_service_status.stdout_lines
  :wq!      
